imports:
    - { resource: service_aliases.yaml }
    - { resource: view.yaml }
    - { resource: systeminfo.yaml }
    - { resource: events.yaml }

parameters:
    support_tools.command.dump_info.class: Ibexa\Bundle\SystemInfo\Command\SystemInfoDumpCommand
    support_tools.system_info.collector_registry.class: Ibexa\Bundle\SystemInfo\SystemInfo\Registry\IdentifierBased
    support_tools.system_info.output_registry.class: Ibexa\Bundle\SystemInfo\SystemInfo\OutputFormatRegistry
    support_tools.system_info.ezc.wrapper.class: Ibexa\Bundle\SystemInfo\SystemInfo\EzcSystemInfoWrapper
    support_tools.system_info.collector.composer.lock_file.class: Ibexa\Bundle\SystemInfo\SystemInfo\Collector\JsonComposerLockSystemInfoCollector
    support_tools.system_info.collector.system.ibexa.class: Ibexa\Bundle\SystemInfo\SystemInfo\Collector\IbexaSystemInfoCollector
    support_tools.system_info.collector.hardware.ezc.class: Ibexa\Bundle\SystemInfo\SystemInfo\Collector\EzcHardwareSystemInfoCollector
    support_tools.system_info.collector.php.ezc.class: Ibexa\Bundle\SystemInfo\SystemInfo\Collector\EzcPhpSystemInfoCollector
    support_tools.system_info.collector.symfony.kernel.config.class: Ibexa\Bundle\SystemInfo\SystemInfo\Collector\ConfigurationSymfonyKernelSystemInfoCollector
    support_tools.system_info.output_format.json.class: Ibexa\Bundle\SystemInfo\SystemInfo\OutputFormat\JsonOutputFormat
    ezplatform_support_tools.system_info.powered_by.name: ''
    ibexa.system_info.ibexa_url_list:
        contact: "https://www.ibexa.co/about-ibexa/contact-us"
        license: "https://www.ibexa.co/software-information/licenses-and-agreements"
        ttl: "https://www.ibexa.co/software-information/licenses-and-agreements/ez-trial-and-test-license-agreement-ez-ttl-v2.1"
        service_life: "https://support.ibexa.co/Public/Service-Life"
        support_service: "https://www.ibexa.co/services/support-maintenance"
        training_service: "https://www.ibexa.co/services/training"
        consulting_service: "https://www.ibexa.co/services/consulting-services"
        ee_product: "https://www.ibexa.co/products"
        install_ee: "https://doc.ibexa.co/en/{ez.release}/getting_started/install_ez_enterprise/"
        doc: "https://doc.ibexa.co"
        update: "https://doc.ibexa.co/en/latest/updating/updating_ez_platform/"
        gpl_faq: "https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#GPLModuleLicense"
        support: "https://support.ibexa.co"
    support_tools.ez_url_list: '%ibexa.system_info.ibexa_url_list%' # BC

services:
    # EventSubscriber
    Ibexa\Bundle\SystemInfo\EventSubscriber\AddXPoweredByHeader:
        arguments: ["%ezplatform_support_tools.system_info.powered_by.name%"]
        tags:
            - { name: kernel.event_subscriber }

    # Console
    support_tools.command.dump_info:
        class: "%support_tools.command.dump_info.class%"
        arguments:
            - "@support_tools.system_info.collector_registry"
            - "@support_tools.system_info.output_registry"
        tags:
            - { name: console.command }

    support_tools.system_info.collector_registry:
        class: "%support_tools.system_info.collector_registry.class%"

    support_tools.system_info.output_registry:
        class: "%support_tools.system_info.output_registry.class%"

    support_tools.system_info.ezc.wrapper:
        class: "%support_tools.system_info.ezc.wrapper.class%"
        lazy: true

    # SystemInfoCollectors
    support_tools.system_info.collector.system.ibexa:
        class: '%support_tools.system_info.collector.system.ibexa.class%'
        arguments:
            $composerCollector: "@support_tools.system_info.collector.composer.lock_file"
            $kernelProjectDir: '%kernel.project_dir%'
            $debug: '%kernel.debug%'
        tags:
            - { name: "support_tools.system_info.collector", identifier: "ibexa" }

    Ibexa\SystemInfo\VersionStability\ComposerVersionStabilityChecker: ~

    Ibexa\SystemInfo\VersionStability\VersionStabilityChecker:
        '@Ibexa\SystemInfo\VersionStability\ComposerVersionStabilityChecker'

    support_tools.system_info.collector.composer.lock_file:
        class: "%support_tools.system_info.collector.composer.lock_file.class%"
        arguments:
            $versionStabilityChecker: '@Ibexa\SystemInfo\VersionStability\VersionStabilityChecker'
            $lockFile: "%kernel.project_dir%/composer.lock"
            $jsonFile: "%kernel.project_dir%/composer.json"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "composer" }

    Ibexa\Bundle\SystemInfo\SystemInfo\Collector\RepositorySystemInfoCollector:
        lazy: true
        autowire: true
        arguments:
            $db: '@ezpublish.persistence.connection'
        tags:
            - { name: "support_tools.system_info.collector", identifier: "repository" }

    support_tools.system_info.collector.hardware.ezc:
        class: "%support_tools.system_info.collector.hardware.ezc.class%"
        arguments:
            - "@support_tools.system_info.ezc.wrapper"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "hardware" }

    support_tools.system_info.collector.php.ezc:
        class: "%support_tools.system_info.collector.php.ezc.class%"
        arguments:
            - "@support_tools.system_info.ezc.wrapper"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "php" }

    support_tools.system_info.collector.symfony.kernel.config:
        class: "%support_tools.system_info.collector.symfony.kernel.config.class%"
        arguments:
            - "@kernel"
            - "%kernel.bundles%"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "symfony_kernel" }

    Ibexa\Bundle\SystemInfo\SystemInfo\Collector\ServicesSystemInfoCollector:
        autowire: true
        tags:
            - { name: support_tools.system_info.collector, identifier: services }

    # SystemInfoOutputFormats
    support_tools.system_info.output_format.json:
        class: "%support_tools.system_info.output_format.json.class%"
        tags:
            - { name: "support_tools.system_info.output_format", format: "json" }

    # Gateways
    Ibexa\SystemInfo\Storage\MetricsProvider:
        alias: Ibexa\SystemInfo\Storage\AggregateMetricsProvider

    Ibexa\SystemInfo\Storage\AggregateMetricsProvider:
        arguments:
            $metrics: !tagged_locator
                tag: !php/const \Ibexa\Bundle\SystemInfo\DependencyInjection\IbexaSystemInfoExtension::METRICS_TAG
                index_by: identifier

    Ibexa\SystemInfo\Storage\Metrics\RepositoryConnectionAwareMetrics:
        abstract: true
        arguments:
            $connection: '@ezpublish.persistence.connection'

    Ibexa\SystemInfo\Storage\Metrics\PublishedContentObjectsCountMetrics:
        parent: Ibexa\SystemInfo\Storage\Metrics\RepositoryConnectionAwareMetrics
        tags:
            -
              name: !php/const \Ibexa\Bundle\SystemInfo\DependencyInjection\IbexaSystemInfoExtension::METRICS_TAG
              identifier: published

    Ibexa\SystemInfo\Storage\Metrics\UsersCountMetrics:
        parent: Ibexa\SystemInfo\Storage\Metrics\RepositoryConnectionAwareMetrics
        tags:
            -
              name: !php/const \Ibexa\Bundle\SystemInfo\DependencyInjection\IbexaSystemInfoExtension::METRICS_TAG
              identifier: users

    Ibexa\SystemInfo\Storage\Metrics\DraftsCountMetrics:
        parent: Ibexa\SystemInfo\Storage\Metrics\RepositoryConnectionAwareMetrics
        tags:
            -
              name: !php/const \Ibexa\Bundle\SystemInfo\DependencyInjection\IbexaSystemInfoExtension::METRICS_TAG
              identifier: drafts

    Ibexa\SystemInfo\Storage\Metrics\VersionsCountMetrics:
        parent: Ibexa\SystemInfo\Storage\Metrics\RepositoryConnectionAwareMetrics
        tags:
            -
              name: !php/const \Ibexa\Bundle\SystemInfo\DependencyInjection\IbexaSystemInfoExtension::METRICS_TAG
              identifier: versions

    Ibexa\SystemInfo\Storage\Metrics\ContentTypesCountMetrics:
        parent: Ibexa\SystemInfo\Storage\Metrics\RepositoryConnectionAwareMetrics
        tags:
            -
              name: !php/const \Ibexa\Bundle\SystemInfo\DependencyInjection\IbexaSystemInfoExtension::METRICS_TAG
              identifier: content_types

    # Services
    Ibexa\SystemInfo\Service\ServiceProviderInterface:
        alias: Ibexa\SystemInfo\Service\AggregateServiceProvider

    Ibexa\SystemInfo\Service\AggregateServiceProvider:
        arguments:
            $service: !tagged_locator
                tag: !php/const \Ibexa\Bundle\SystemInfo\DependencyInjection\IbexaSystemInfoExtension::SERVICE_TAG
                index_by: identifier

    Ibexa\SystemInfo\Service\SearchEngineServiceInfo:
        arguments:
            $repositoryConfigProvider: '@ezpublish.api.repository_configuration_provider'
        tags:
            - name: !php/const \Ibexa\Bundle\SystemInfo\DependencyInjection\IbexaSystemInfoExtension::SERVICE_TAG
              identifier: searchEngine

    Ibexa\SystemInfo\Service\HttpCacheServiceInfo:
        arguments:
            $purgeType: '%purge_type%'
        tags:
            - name: !php/const \Ibexa\Bundle\SystemInfo\DependencyInjection\IbexaSystemInfoExtension::SERVICE_TAG
              identifier: httpCacheProxy

    Ibexa\SystemInfo\Service\PersistenceCacheServiceInfo:
        arguments:
            $configResolver: '@ezpublish.config.resolver'
        tags:
            - name: !php/const \Ibexa\Bundle\SystemInfo\DependencyInjection\IbexaSystemInfoExtension::SERVICE_TAG
              identifier: persistenceCacheAdapter
