services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\SystemInfo\Tab\SystemInfo\TabFactory:
        arguments:
            $httpKernelRuntime: '@twig.runtime.httpkernel'

    ez.support.tools.systeminfo.tab_groups:
        parent: Ibexa\AdminUi\Component\TabsComponent
        arguments:
            $template: '@@ezdesign/ui/tab/system_info.html.twig'
            $groupIdentifier: 'systeminfo'
        tags:
            - { name: ibexa.admin_ui.component, group: 'systeminfo-tab-groups' }
