services:
    Ibexa\Bundle\SystemInfo\Controller\SystemInfoController:
        parent: Ibexa\Contracts\AdminUi\Controller\Controller
        autowire: true
        arguments:
            - '@Ibexa\Bundle\SystemInfo\SystemInfo\Registry\IdentifierBased'
        tags:
            - { name: controller.service_arguments }

    ibexa.support_tools.view.controller:
        alias: Ibexa\Bundle\SystemInfo\Controller\SystemInfoController
        public: true

    Ibexa\Bundle\SystemInfo\View\SystemInfoViewBuilder:
        class: Ibexa\Bundle\SystemInfo\View\SystemInfoViewBuilder
        arguments:
            - '@Ibexa\Core\MVC\Symfony\View\Configurator\ViewProvider'
            - '@Ibexa\Bundle\SystemInfo\SystemInfo\Registry\IdentifierBased'
        tags:
            - { name: ibexa.view_builder }

    ibexa.support_tools.view.system_info.provider:
        class: "%ezpublish.view_provider.configured.class%"
        arguments: ['@ibexa.support_tools.view.matcher_factory']
        tags:
            - {name: ezpublish.view_provider, type: 'Ibexa\Bundle\SystemInfo\View\SystemInfoView', priority: 10}

    ibexa.support_tools.view.matcher_factory:
        class: "%ezpublish.view.matcher_factory.class%"
        arguments:
            - '@Ibexa\Bundle\Core\Matcher\ViewMatcherRegistry'
            - '@ibexa.api.repository'
            - 'Ibexa\Bundle\SystemInfo\View\Matcher'

    ibexa.support_tools.view.matcher_factory.dynamically_configured:
        class: Ibexa\Core\MVC\Symfony\Matcher\DynamicallyConfiguredMatcherFactoryDecorator
        decorates: ibexa.support_tools.view.matcher_factory
        arguments:
            $innerConfigurableMatcherFactory: '@ibexa.support_tools.view.matcher_factory.dynamically_configured.inner'
            $configResolver: '@ibexa.config.resolver'
            $parameterName: system_info_view
